site_name: ESP8266 IoT Workshop
site_description: >-
  IoT workshop based on ESP8266, a DHT11/22 and NeoPixel RGB LED with data analysis on the IBM Cloud.
site_url: https://binnes.github.io/esp8266Workshop/
site_author: Brian Innes
repo_name: binnes/esp8266Workshop
repo_url: https://github.com/binnes/esp8266Workshop
theme:
    name: material
use_directory_urls: false
plugins:
  - search
  - with-pdf:
      cover_subtitle: using a DHT11/22 and NeoPixel RGB LED with data analysis on the IBM Cloud
      output_path: pdf/esp8266Workshop.pdf
markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.superfences
  - pymdownx.highlight
extra_css:
    - css/extra.css
    - css/pdf-print.css
nav:
  - Home: index.md
  - Part 1: 
    - Intro: part1/README.md
    - Setup for the Workshop: part1/PREREQ.md
    - Intro to ESP8266: part1/FIRSTAPP.md
    - ESP8266 WiFi: part1/WIFI.md
    - LED Light: part1/LED.md
    - DHT Sensor: part1/DHT.md
    - IBM Cloud: part1/IOTCLOUD.md
  - Part 2: 
    - Intro: part2/README.md
    - MQTT Broker: part2/BROKER.md
    - Creating the ESP8266 Application: part2/APP.md
    - Intro to MQTT: part2/MQTT.md
    - Internet Security: part2/SECURITY.md
    - IoT Security: part2/CERT1.md
    - Additional Security considerations: part2/CERT2.md
  - Part 3:
    - Intro: part3/README.md
    - Node-RED: part3/NODERED.md
    - Sensor Data: part3/DHTDATA.md
    - Dashboards: part3/DASHBOARD.md
    - Database: part3/CLOUDANT.md
    - Historical Data: part3/HISTORY.md
    - Reporting interval: part3/INTERVAL.md
    - Remote LED control: part3/LED.md
  - Part 4: 
    - Intro: part4/README.md
    - Watson Studio: part4/STUDIO.md
    - Create Training Data: part4/TRAINING.md
    - Jupyter Notebooks: part4/JUPYTER.md
    - Run model on device: part4/MODEL.md
    - Workshop Summary : part4/SUMMARY.md
  - Additional:
    - Agenda: AGENDA.md
    - Resources: RESOURCES.md
google_analytics: ['UA-172132667-1', 'binnes.github.io/esp8266Workshop']
